### ISSUE TITLE
[bam2vcf] - Cannot find the script

### ISSUE THREAD

**Issue by kerimsecener** [phoenixding/tbsp#2]
Hi,

I see you had provided a bam2vcf.py script. However when I click on the link, it says it's "deleted by the owner".
Could you maybe provide it again ?

Thanks !

**Comment by phoenixding** [comment]
@kerimsecener 
Thank you for reporting this issue.
I have accidentally deleted  the code. 
Please use the following link, I will fix the github page later. 
https://my.pcloud.com/publink/show?code=XZH5iFkZz0uXbbvQ8AQznXWoRXBOS0VJUtuV
