### ISSUE TITLE
encoding error byte 0x80

### ISSUE THREAD

**Issue by vincent-van-hoef** [phoenixding/tbsp#3]
First of all, thanks for a great package! 

Running the docker version of tbsp throws a UnicodeDecodeError: utf-8 codec can't decode byte 0x80... Changing line 21 in File.py to f=open(self.name,'r', errors="ignore") seemingly resolved the issue. Don't know if it's a local issue (but docker?) or not but I just thought to mention it here...

**Comment by phoenixding** [comment]
@vincent-van-hoef 
Thanks for reporting this issue and also for telling me the potential causes! 
I haven't encountered this issue before, I will check it out and update the package accordingly.
