### ISSUE TITLE
I don't manage to find the 'help' from bam2vcf

### ISSUE THREAD

**Issue by aureliebousard** [phoenixding/tbsp#4]
Dear Ding,

I upload the bam2vcf but get this error when I try to see the 'help' or that I try running it.

Traceback (most recent call last):
  File "bam2vcf.py", line 3, in <module>
    from File import *
ModuleNotFoundError: No module named 'File'

Do you have any idea what is wrong?

Thank you

Aurélie

**Comment by phoenixding** [comment]
@aureliebousard 
Thank you for reporting this issue.
File is an old library that I used for developing.  It's not needed for running the script.
You can simply delete this line and then it should be working. 

For the help of the script, please type python bam2vcf.py --help 

Please let me know if you have any further questions.
